GET http://localhost:4000/

###
GET http://localhost:4000/task

###
POST http://localhost:4000/task
Accept: application/json
Content-Type: application/json

{
    "name": "Task 3",
    "description": "Task Fisica",
    "isActive": true
}

###
GET http://localhost:4000/task/3