GET http://localhost:3000/

###
GET http://localhost:3000/task

###
POST http://localhost:3000/task
Accept: application/json
Content-Type: application/json

{
    "name": "Task 3",
    "description": "Task Fisica",
    "isActive": true
}

###
GET http://localhost:3000/task/2

###
PATCH http://localhost:3000/task/3
Accept: application/json
Content-Type: application/json

{
    
    "description": "Task Matematicas",
    "isActive": true
}

###
DELETE http://localhost:3000/task/4