GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoid2lsbHlAbWFpbC5jb20iLCJpYXQiOjE3NzU3NjI0ODUsImV4cCI6MTc3NTg0ODg4NX0.XdZh5H9to01M_eIgHQLUniW56Pd1827osqlb4nL0EIY

###
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "willy",
    "email": "willy@mail.com",
    "password" : "0987654321"
}

###
GET http://localhost:3000/user/2

###
PATCH http://localhost:3000/user/1
Content-Type: application/json

{
    "name": "admin5",
    "email": "admin2@mail.com",
    "password" : "1234567890"
}

###
DELETE http://localhost:3000/user/3